create table if not exists public.favorite_books (
  id bigint generated by default as identity primary key,
  title text unique not null,
  author text not null,
  created_at timestamptz not null default now()
);

alter table public.favorite_books enable row level security;

drop policy if exists "Public can read favorite books" on public.favorite_books;

create policy "Public can read favorite books"
on public.favorite_books
for select
to anon
using (true);

insert into public.favorite_books (title, author)
values
  ('Pride and Prejudice', 'Jane Austen'),
  ('The Little Prince', 'Antoine de Saint-Exupéry'),
  ('The Hobbit', 'J. R. R. Tolkien')
on conflict (title) do nothing;
